server:
  port: 8100

jwt:
  secret: ${JWT_SECRET}

spring:
  activemq:
    broker-url: tcp://localhost:65130
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
    queue:
      game-session: game-session-queue
  config:
    activate:
      on-profile: local
  security:
    user:
      name: user
      password: localpass

jms:
  queue:
    game-session: game-session-queue

logging:
  level:
    org.springframework: DEBUG
    com.kanionland: DEBUG